name: experimental
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v4

      - name: custom
        id: hello
        uses: baykovr/hello-world-docker-action@e6a578daea5f68d2d0eb7a14acc2b85cd3dff8a5
        with:
          who-to-greet: 'neat'
      - name: fetch output
        run: echo "${{ steps.hello.outputs.time }}"
