name: make
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: ./.github/workflows/.build.yml
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
