name: make
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build
        uses: actions/checkout@v4
      - name: nix-isntall
        uses: cachix/install-nix-action@v25
      - run: nix build
      - run: nix flake check

