name: releases
on:
  push:
    branches:
      - releases

jobs:
  build:
    uses: ./.github/workflows/.build.yml
  upload:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: st
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: st
          tag_name: latest
